import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import SurveyForm from "@components/Survey/form";
import MainBody from "@components/mainbody";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Tip me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <SurveyForm /> */}
      <MainBody />
    </>
  );
};

export default Home;
